### ISSUE TITLE
Please consider extracting less compiler from lein-less plugin

### ISSUE THREAD

**Issue by Flamefork** [montoux/lein-less#11]
It would be really great to have `less` compiler independent from leiningen.

Use case: I'm trying to get _some_ less compiler to work as a ring middleware.

Maybe it could be inline with https://github.com/less/less.js/issues/2063 work?

**Comment by sfnelson** [comment]
Sorry I don't have anything to report. If anyone makes progress on running the less 2.x branch on the JVM let me know.
