### ISSUE TITLE
lein less auto throws a file not found exception

### ISSUE THREAD

**Issue by danielytics** [montoux/lein-less#12]
When running `lein less once` it picks up and compiles my less file as expected, but when running `lein less auto` it throws a `FileNotFoundException` on the .less file (the exception has the full path to the file and it definitely exists).

**Comment by danielytics** [comment]
It turns out `lein less auto` works fine when the file is edited with some editors but not when I edit with `vim`. I guess whatever way my `vim` is writing the files is breaking it (watcher sees the change but the file is deleted and rewritten maybe?) I'll investigate more before closing this issue.

**Comment by sfnelson** [comment]
I'm not interested in debouncing editor changes. Feel free to reopen if you can identify a particular issue with the way `lein-less` is reading files.
