### ISSUE TITLE
Separate watch and compile paths?

### ISSUE THREAD

**Issue by sickill** [montoux/lein-less#14]
I have this less source tree (`src/less`):

    |-- main.less
    |-- modules
    |   |-- font.less
    |   |-- overlay.less
    |   `-- theme-base.less
    |-- partials
    |   |-- base.less
    |   |-- control-bar.less
    |   |-- loader.less
    |   |-- loading-overlay.less
    |   |-- player.less
    |   |-- rgb.less
    |   |-- start-overlay.less
    |   `-- terminal.less
    `-- themes
        |-- seti.less
        |-- solarized-dark.less
        |-- solarized-light.less
        `-- tango.less

Note that I have top-level `main.less` file which imports files from `partials/` and `modules/` directories and I only care about the result of the compilation of `main.less`.

The problem is some partials depend on mixins defined in `base.less` / `modules/*.less` and when lein-less tries to compile the individual partials it fails due to missing mixins:

```
Compiling {less} css:
Found {less} source paths:
  src/less
  src/less/modules
  src/less/partials
  src/less/themes
Watching for changes...
src/less/main.less => resources/public/css/main.css
src/less/modules/font.less => resources/public/css/modules/font.css
src/less/modules/overlay.less => resources/public/css/modules/overlay.css
src/less/modules/theme-base.less => resources/public/css/modules/theme-base.css
src/less/partials/base.less => resources/public/css/partials/base.css
src/less/partials/control-bar.less => resources/public/css/partials/control-bar.css
src/less/partials/loader.less => resources/public/css/partials/loader.css
src/less/partials/loading-overlay.less => resources/public/css/partials/loading-overlay.css
NameError: .player-overlay is undefined in /Users/sickill/code/asciinema/player/src/less/partials/loading-overlay.less on line 3, column 5:
2   .loading {
3     .player-overlay;
4

src/less/partials/player.less => resources/public/css/partials/player.css
src/less/partials/rgb.less => resources/public/css/partials/rgb.css
src/less/partials/start-overlay.less => resources/public/css/partials/start-overlay.css
NameError: .player-overlay is undefined in /Users/sickill/code/asciinema/player/src/less/partials/start-overlay.less on line 3, column 5:
2   .start-prompt {
3     .player-overlay;
4

...
```

What do you think about separating "watch paths" from "compile paths", so when you `lein less auto` and any file in "watch paths" changes it compiles the files/dirs specified by "compile paths"?

Something like this could be flexible enough:

```clojure
:less {:source-paths ["src/less"]
       :compile-paths ["src/less/main.less"] ; defaults to source-paths when not set
       :target-path "resources/public/css"})
```

**Comment by sfnelson** [comment]
If you add an underscore to the files you don't want to compile then they won't produce an artefact, e.g.

```modules/_font.less```

**Comment by sickill** [comment]
Eh, right.. I don't know why I didn't think about it. Sorry for the noise. Thanks!
